# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-26 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneapp', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='baddress',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='baddress2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='bcity',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='bfirst_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='blast_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='bstate',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='bzipcode',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='expiration',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='saddress',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='saddress2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='scity',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='security',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sfirst_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='slast_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sstate',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='szipcode',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
    ]
